### ISSUE TITLE
Make this available for python projects

### ISSUE THREAD

**Issue by gautamkrishnar** [WeAllJS/weallcontribute#5]
I think we must not limit this project to nodejs apps/modules. After installing this tool globally, it must be able to create contributing.md for python  projects as well. I will be happy to implement it if you are okay with this change.
cc: @aredridel @zkat @passcod @cjwilburn @Charlotteis

**Comment by zkat** [comment]
I don't mind this at all, as long as it prioritizes `package.json` if both that and python metadata are present, and if it doesn't break node integration :)

Thanks for the offer! This would be a cool patch. :D

**Comment by gautamkrishnar** [comment]
Yes i will make sure that it doesn't break the node integration. I will try to detect the repo and other info from the setup.py script in python, if it is present and update the instructions of contribute.md for python.

**Comment by gautamkrishnar** [comment]
@zkat shall i also add a `-i` (interactive version) flag to the command line? so that the user can manually type the repo url.

**Comment by zkat** [comment]
@gautamkrishnar do you think that's worth doing even though you can already provide the repo as a CLI argument? (`weallcontribute zkat/cacache` works, for example). Not sure what the gain would be.

**Comment by gautamkrishnar** [comment]
@zkat Thanks for letting me know. Then it would be ok, we dont need to add an interactive mode. :+1:

**Comment by zkat** [comment]
Interest in this seems to have waned. Just gonna close it.
