### ISSUE TITLE
Why does cipm need a separate tool?

### ISSUE THREAD

**Issue by styfle** [WeAllJS/weallcontribute#9]
Why does `cipm` need to be a separate tool?
Couldn't it be a command line flag for the existing `npm` tool?

**Comment by zkat** [comment]
I think you've got the wrong repo. The repo for cipm is over at https://github.com/zkat/cipm

**Comment by styfle** [comment]
@zkat I thought so too but the contributing guidelines lead me here.

https://github.com/zkat/cipm/blob/latest/CONTRIBUTING.md
